### ISSUE TITLE
Ability to generate nonce and include those in CSP

### ISSUE THREAD

**Issue by barryvanveen** [BePsvPT/csp-builder#1]
Hi BePsvPT,

I've been using the secure-headers package for some time now and like it a lot, thanks for the good work!

One feature that I'd like to use in my CSP headers are nonces. The idea is that the server generates a random string that is unique for each request and not guessable. You include "nonce-YourRandomString" as part of the script-src or style-src directives. Then you can add the nonce to your script- or style tags like so: <script nonce="YourRandomString">. This allows you to enforce stricter CSP rules because you can whitelist scripts very specifically.

A general description of what needs to be done:
- Add config options to enable the generation and inclusion of a nonce-value.
- Generate the nonce-value using random_bytes.
- Include the nonce-value into the CSP-directives, if it is enabled in the configuration.

Would you be interested in a PR that adds this functionality? I'd also like to hear your ideas about implementation details, if you have any.

Regards,

Barry

**Comment by barryvanveen** [comment]
If I make a PR to add this functionality, would you consider merging it into this repository?

**Comment by BePsvPT** [comment]
@barryvanveen, I'm so busy on a project recently and feel sorry for not handling this issue. If you can open a pull request, I will appreciate it alot.
